package org.pmp.sms.vo;

// Generated 2012-5-7 16:29:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SMSCompany generated by hbm2java
 */
public class SMSCompany implements java.io.Serializable {

    private Integer smscId;
    private String smscName;
    private Integer comId;
    private String smsUpUrl;
    private String smsDownUrl;
    private String username;
    private String password;
    private String extendCode;
    private Set SMSSends = new HashSet(0);

    public SMSCompany() {
    }

    public SMSCompany(Integer smscId) {
	this.smscId = smscId;
    }

    public SMSCompany(Integer smscId, String smscName, Integer comId,
	    String smsUpUrl, String smsDownUrl, String username,
	    String password, String extendCode, Set SMSSends) {
	this.smscId = smscId;
	this.smscName = smscName;
	this.comId = comId;
	this.smsUpUrl = smsUpUrl;
	this.smsDownUrl = smsDownUrl;
	this.username = username;
	this.password = password;
	this.extendCode = extendCode;
	this.SMSSends = SMSSends;
    }

    public Integer getSmscId() {
	return this.smscId;
    }

    public void setSmscId(Integer smscId) {
	this.smscId = smscId;
    }

    public String getSmscName() {
	return this.smscName;
    }

    public void setSmscName(String smscName) {
	this.smscName = smscName;
    }

    public Integer getComId() {
	return this.comId;
    }

    public void setComId(Integer comId) {
	this.comId = comId;
    }

    public String getSmsUpUrl() {
	return this.smsUpUrl;
    }

    public void setSmsUpUrl(String smsUpUrl) {
	this.smsUpUrl = smsUpUrl;
    }

    public String getSmsDownUrl() {
	return this.smsDownUrl;
    }

    public void setSmsDownUrl(String smsDownUrl) {
	this.smsDownUrl = smsDownUrl;
    }

    public String getUsername() {
	return this.username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    public String getExtendCode() {
	return this.extendCode;
    }

    public void setExtendCode(String extendCode) {
	this.extendCode = extendCode;
    }

    public Set getSMSSends() {
	return this.SMSSends;
    }

    public void setSMSSends(Set SMSSends) {
	this.SMSSends = SMSSends;
    }

}
